<?php
//后台登录
Route::get('admin/login','Admin\auth\LoginController@index');
//后台登录表单提交
Route::post('admin/auth/login','Admin\auth\LoginController@check');
//后台主页
Route::get('admin/index','Admin\index\IndexController@index');
//产品管理
Route::get('admin/commodity','Admin\index\CommodityController@index');
//首页推荐
Route::get('admin/recommend','Admin\index\CommodityController@recommend');
//图片管理
Route::get('admin/img','Admin\index\CommodityController@img');
//分类管理
Route::get('admin/classification','Admin\index\CommodityController@classification');
//评论列表
Route::get('admin/comment','Admin\index\CommodityController@comment');
//意见反馈
Route::get('admin/opinion','Admin\index\CommodityController@opinion');
//会员列表
Route::get('admin/vip','Admin\index\CommodityController@vip');
//等级管理
Route::get('admin/grade','Admin\index\CommodityController@grade');
//角色管理
Route::get('admin/character','Admin\index\CommodityController@character');
//管理员列表
Route::get('admin/admin','Admin\index\CommodityController@admin');
